### ISSUE TITLE
Bad Games

### ISSUE THREAD

**Issue by JirkaDellOro** [AionixX/GameZone#1]
Bitschieber und Cublex gehören zu den besten Games die wir haben.  Die müssen definitiv drin bleiben.

**Comment by JirkaDellOro** [comment]
Diese Spiele sollen auch drin bleiben:

Star Shoot
Extreme Exterminator
Autumn Leaves
Chibi Dressup

**Comment by AionixX** [comment]
Alles klar packe ich mit rein. Ist die Landing Page die die Frau Rösler geschickt hat für dich so in Ordnung? Gesendet von Mail für Windows 10 Von: JirkaDellOroGesendet: Mittwoch, 8. Juli 2020 09:13An: AionixX/GameZoneCc: SubscribedBetreff: Re: [AionixX/GameZone] Bad Games (#1) Diese Spiele sollen auch drin bleiben:Star ShootExtreme ExterminatorAutumn LeavesChibi Dressup—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by JirkaDellOro** [comment]
Ist OK.

Besser nicht per Mail auf Issues antworten
